export interface Tire {
  id: string;
  brand: string;
  model: string;
  size: string;
  diameter: number;
  type: "Passenger" | "All-Terrain" | "Mud-Terrain" | "Trailer" | "All-Season";
  price: number;
  priceType: "per set" | "each";
  inStock: boolean;
  loadRating?: string;
  speedRating?: string;
}

export const TIRES: Tire[] = [
  {
    id: "1",
    brand: "Zeta",
    model: "Pero H/T",
    size: "265/70R17",
    diameter: 17,
    type: "All-Terrain",
    price: 560,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "2",
    brand: "RoadOne",
    model: "Cavalry M/T",
    size: "275/65R18",
    diameter: 18,
    type: "Mud-Terrain",
    price: 720,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "3",
    brand: "Cosmo",
    model: "RC-17",
    size: "205/55R16",
    diameter: 16,
    type: "Passenger",
    price: 320,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "4",
    brand: "Goodride",
    model: "SL369",
    size: "255/75R17",
    diameter: 17,
    type: "All-Terrain",
    price: 640,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "5",
    brand: "MasterTrack",
    model: "Regner H/P",
    size: "225/45R18",
    diameter: 18,
    type: "Passenger",
    price: 440,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "6",
    brand: "Freedom",
    model: "Hauler ST",
    size: "205/75R15",
    diameter: 15,
    type: "Trailer",
    price: 280,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "7",
    brand: "Centara",
    model: "Sport A/S",
    size: "235/55R19",
    diameter: 19,
    type: "All-Season",
    price: 580,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "8",
    brand: "Zeetex",
    model: "HP6000 ECO",
    size: "215/60R16",
    diameter: 16,
    type: "Passenger",
    price: 360,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "9",
    brand: "Blackhawk",
    model: "Street-H HH01",
    size: "225/40R18",
    diameter: 18,
    type: "Passenger",
    price: 480,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "10",
    brand: "Lionhart",
    model: "LH-Five",
    size: "245/45R20",
    diameter: 20,
    type: "Passenger",
    price: 620,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "11",
    brand: "LionSport",
    model: "GP",
    size: "275/55R20",
    diameter: 20,
    type: "All-Terrain",
    price: 760,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "12",
    brand: "Petlas",
    model: "Explero PT411",
    size: "265/60R18",
    diameter: 18,
    type: "All-Terrain",
    price: 680,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "13",
    brand: "Haida",
    model: "HD819",
    size: "195/65R15",
    diameter: 15,
    type: "Passenger",
    price: 280,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "14",
    brand: "Fortune",
    model: "FSR-305",
    size: "305/55R20",
    diameter: 20,
    type: "Mud-Terrain",
    price: 840,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "15",
    brand: "Zeta",
    model: "Pero M/T",
    size: "33x12.5R20",
    diameter: 20,
    type: "Mud-Terrain",
    price: 920,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "16",
    brand: "RoadOne",
    model: "Cavalry A/T",
    size: "245/70R17",
    diameter: 17,
    type: "All-Terrain",
    price: 600,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "17",
    brand: "Cosmo",
    model: "Mud Kicker",
    size: "35x12.5R18",
    diameter: 18,
    type: "Mud-Terrain",
    price: 1040,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "18",
    brand: "Goodride",
    model: "Radial SL 369",
    size: "235/85R16",
    diameter: 16,
    type: "All-Terrain",
    price: 520,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "19",
    brand: "Freedom",
    model: "Hauler ST Radial",
    size: "225/75R15",
    diameter: 15,
    type: "Trailer",
    price: 240,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "20",
    brand: "Blackhawk",
    model: "Terra H/T",
    size: "265/65R17",
    diameter: 17,
    type: "All-Terrain",
    price: 560,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "21",
    brand: "Lionhart",
    model: "LH-TEN",
    size: "275/70R18",
    diameter: 18,
    type: "All-Terrain",
    price: 720,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "22",
    brand: "MasterTrack",
    model: "Terrano M/T",
    size: "315/70R17",
    diameter: 17,
    type: "Mud-Terrain",
    price: 880,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "23",
    brand: "Petlas",
    model: "Full Power PT825",
    size: "185/70R14",
    diameter: 14,
    type: "Trailer",
    price: 200,
    priceType: "per set",
    inStock: true,
  },
  {
    id: "24",
    brand: "Haida",
    model: "HD918",
    size: "265/70R16",
    diameter: 16,
    type: "All-Terrain",
    price: 480,
    priceType: "per set",
    inStock: true,
  },
];

export const BRANDS = [...new Set(TIRES.map((t) => t.brand))].sort();
export const TYPES = [...new Set(TIRES.map((t) => t.type))].sort();
export const DIAMETERS = [...new Set(TIRES.map((t) => t.diameter))].sort(
  (a, b) => a - b,
);
